// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: rpc/proto/raag.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rpc_proto_raag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{0}
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Multiaddr     string                 `protobuf:"bytes,1,opt,name=multiaddr,proto3" json:"multiaddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetMultiaddr() string {
	if x != nil {
		return x.Multiaddr
	}
	return ""
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{2}
}

func (x *DisconnectRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type BootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Multiaddr     string                 `protobuf:"bytes,1,opt,name=multiaddr,proto3" json:"multiaddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{3}
}

func (x *BootstrapRequest) GetMultiaddr() string {
	if x != nil {
		return x.Multiaddr
	}
	return ""
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{4}
}

// Peer
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Connected     bool                   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_rpc_proto_raag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{5}
}

func (x *PeerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PeerInfo) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type PeerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerListResponse) Reset() {
	*x = PeerListResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerListResponse) ProtoMessage() {}

func (x *PeerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerListResponse.ProtoReflect.Descriptor instead.
func (*PeerListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{6}
}

func (x *PeerListResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeersInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Self               map[string]string      `protobuf:"bytes,1,rep,name=self,proto3" json:"self,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConnectedPeers     []*PeerInfo            `protobuf:"bytes,2,rep,name=connected_peers,json=connectedPeers,proto3" json:"connected_peers,omitempty"`
	ConnectedPeerCount int32                  `protobuf:"varint,3,opt,name=connected_peer_count,json=connectedPeerCount,proto3" json:"connected_peer_count,omitempty"`
	KnownPeers         []*PeerInfo            `protobuf:"bytes,4,rep,name=known_peers,json=knownPeers,proto3" json:"known_peers,omitempty"`
	KnownPeerCount     int32                  `protobuf:"varint,5,opt,name=known_peer_count,json=knownPeerCount,proto3" json:"known_peer_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PeersInfoResponse) Reset() {
	*x = PeersInfoResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersInfoResponse) ProtoMessage() {}

func (x *PeersInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersInfoResponse.ProtoReflect.Descriptor instead.
func (*PeersInfoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{7}
}

func (x *PeersInfoResponse) GetSelf() map[string]string {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *PeersInfoResponse) GetConnectedPeers() []*PeerInfo {
	if x != nil {
		return x.ConnectedPeers
	}
	return nil
}

func (x *PeersInfoResponse) GetConnectedPeerCount() int32 {
	if x != nil {
		return x.ConnectedPeerCount
	}
	return 0
}

func (x *PeersInfoResponse) GetKnownPeers() []*PeerInfo {
	if x != nil {
		return x.KnownPeers
	}
	return nil
}

func (x *PeersInfoResponse) GetKnownPeerCount() int32 {
	if x != nil {
		return x.KnownPeerCount
	}
	return 0
}

type KnownPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownPeersResponse) Reset() {
	*x = KnownPeersResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownPeersResponse) ProtoMessage() {}

func (x *KnownPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownPeersResponse.ProtoReflect.Descriptor instead.
func (*KnownPeersResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{8}
}

func (x *KnownPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Event         string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerEvent) Reset() {
	*x = PeerEvent{}
	mi := &file_rpc_proto_raag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerEvent) ProtoMessage() {}

func (x *PeerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerEvent.ProtoReflect.Descriptor instead.
func (*PeerEvent) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{9}
}

func (x *PeerEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerEvent) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PeerEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

// Library
type LibrarySong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,3,opt,name=album,proto3" json:"album,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Cid           string                 `protobuf:"bytes,5,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibrarySong) Reset() {
	*x = LibrarySong{}
	mi := &file_rpc_proto_raag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibrarySong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibrarySong) ProtoMessage() {}

func (x *LibrarySong) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibrarySong.ProtoReflect.Descriptor instead.
func (*LibrarySong) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{10}
}

func (x *LibrarySong) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LibrarySong) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *LibrarySong) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *LibrarySong) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LibrarySong) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type LibraryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*LibrarySong         `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryListResponse) Reset() {
	*x = LibraryListResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryListResponse) ProtoMessage() {}

func (x *LibraryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryListResponse.ProtoReflect.Descriptor instead.
func (*LibraryListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{11}
}

func (x *LibraryListResponse) GetSongs() []*LibrarySong {
	if x != nil {
		return x.Songs
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{12}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type LibrarySearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*LibrarySong         `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibrarySearchResponse) Reset() {
	*x = LibrarySearchResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibrarySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibrarySearchResponse) ProtoMessage() {}

func (x *LibrarySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibrarySearchResponse.ProtoReflect.Descriptor instead.
func (*LibrarySearchResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{13}
}

func (x *LibrarySearchResponse) GetSongs() []*LibrarySong {
	if x != nil {
		return x.Songs
	}
	return nil
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{14}
}

func (x *AddRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RescanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scanned       int32                  `protobuf:"varint,1,opt,name=scanned,proto3" json:"scanned,omitempty"`
	Added         int32                  `protobuf:"varint,2,opt,name=added,proto3" json:"added,omitempty"`
	Removed       int32                  `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescanResponse) Reset() {
	*x = RescanResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanResponse) ProtoMessage() {}

func (x *RescanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanResponse.ProtoReflect.Descriptor instead.
func (*RescanResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{16}
}

func (x *RescanResponse) GetScanned() int32 {
	if x != nil {
		return x.Scanned
	}
	return 0
}

func (x *RescanResponse) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *RescanResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

// Player
type PlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayRequest) Reset() {
	*x = PlayRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRequest) ProtoMessage() {}

func (x *PlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRequest.ProtoReflect.Descriptor instead.
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{17}
}

func (x *PlayRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PlayRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type VolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        int32                  `protobuf:"varint,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeRequest) Reset() {
	*x = VolumeRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRequest) ProtoMessage() {}

func (x *VolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRequest.ProtoReflect.Descriptor instead.
func (*VolumeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{18}
}

func (x *VolumeRequest) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type SeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeekRequest) Reset() {
	*x = SeekRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekRequest) ProtoMessage() {}

func (x *SeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekRequest.ProtoReflect.Descriptor instead.
func (*SeekRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{19}
}

func (x *SeekRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type QueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         []*LibrarySong         `protobuf:"bytes,1,rep,name=queue,proto3" json:"queue,omitempty"`
	CurrentIndex  int32                  `protobuf:"varint,2,opt,name=current_index,json=currentIndex,proto3" json:"current_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueResponse) Reset() {
	*x = QueueResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueResponse) ProtoMessage() {}

func (x *QueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueResponse.ProtoReflect.Descriptor instead.
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{20}
}

func (x *QueueResponse) GetQueue() []*LibrarySong {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *QueueResponse) GetCurrentIndex() int32 {
	if x != nil {
		return x.CurrentIndex
	}
	return 0
}

type NowPlayingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *LibrarySong           `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Playing       bool                   `protobuf:"varint,4,opt,name=playing,proto3" json:"playing,omitempty"`
	Volume        int32                  `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowPlayingResponse) Reset() {
	*x = NowPlayingResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowPlayingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowPlayingResponse) ProtoMessage() {}

func (x *NowPlayingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowPlayingResponse.ProtoReflect.Descriptor instead.
func (*NowPlayingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{21}
}

func (x *NowPlayingResponse) GetSong() *LibrarySong {
	if x != nil {
		return x.Song
	}
	return nil
}

func (x *NowPlayingResponse) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *NowPlayingResponse) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *NowPlayingResponse) GetPlaying() bool {
	if x != nil {
		return x.Playing
	}
	return false
}

func (x *NowPlayingResponse) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type PlayerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,3,opt,name=album,proto3" json:"album,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Volume        float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Playing       bool                   `protobuf:"varint,7,opt,name=playing,proto3" json:"playing,omitempty"`
	Paused        bool                   `protobuf:"varint,8,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEvent) Reset() {
	*x = PlayerEvent{}
	mi := &file_rpc_proto_raag_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEvent) ProtoMessage() {}

func (x *PlayerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEvent.ProtoReflect.Descriptor instead.
func (*PlayerEvent) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PlayerEvent) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *PlayerEvent) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *PlayerEvent) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PlayerEvent) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *PlayerEvent) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *PlayerEvent) GetPlaying() bool {
	if x != nil {
		return x.Playing
	}
	return false
}

func (x *PlayerEvent) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

// Playlist
type PlaylistSongsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistSongsRequest) Reset() {
	*x = PlaylistSongsRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistSongsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistSongsRequest) ProtoMessage() {}

func (x *PlaylistSongsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistSongsRequest.ProtoReflect.Descriptor instead.
func (*PlaylistSongsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{23}
}

func (x *PlaylistSongsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlaylistSongsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*LibrarySong         `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistSongsResponse) Reset() {
	*x = PlaylistSongsResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistSongsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistSongsResponse) ProtoMessage() {}

func (x *PlaylistSongsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistSongsResponse.ProtoReflect.Descriptor instead.
func (*PlaylistSongsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{24}
}

func (x *PlaylistSongsResponse) GetSongs() []*LibrarySong {
	if x != nil {
		return x.Songs
	}
	return nil
}

type PlaylistCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistCreateRequest) Reset() {
	*x = PlaylistCreateRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistCreateRequest) ProtoMessage() {}

func (x *PlaylistCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistCreateRequest.ProtoReflect.Descriptor instead.
func (*PlaylistCreateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{25}
}

func (x *PlaylistCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlaylistDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistDeleteRequest) Reset() {
	*x = PlaylistDeleteRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistDeleteRequest) ProtoMessage() {}

func (x *PlaylistDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistDeleteRequest.ProtoReflect.Descriptor instead.
func (*PlaylistDeleteRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{26}
}

func (x *PlaylistDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlaylistListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistListResponse) Reset() {
	*x = PlaylistListResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistListResponse) ProtoMessage() {}

func (x *PlaylistListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistListResponse.ProtoReflect.Descriptor instead.
func (*PlaylistListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{27}
}

func (x *PlaylistListResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type PlaylistAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SongPath      string                 `protobuf:"bytes,2,opt,name=song_path,json=songPath,proto3" json:"song_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistAddRequest) Reset() {
	*x = PlaylistAddRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistAddRequest) ProtoMessage() {}

func (x *PlaylistAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistAddRequest.ProtoReflect.Descriptor instead.
func (*PlaylistAddRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{28}
}

func (x *PlaylistAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlaylistAddRequest) GetSongPath() string {
	if x != nil {
		return x.SongPath
	}
	return ""
}

type PlaylistRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistRemoveRequest) Reset() {
	*x = PlaylistRemoveRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistRemoveRequest) ProtoMessage() {}

func (x *PlaylistRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistRemoveRequest.ProtoReflect.Descriptor instead.
func (*PlaylistRemoveRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{29}
}

func (x *PlaylistRemoveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlaylistRemoveRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// Config
type ConfigGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigGetResponse) Reset() {
	*x = ConfigGetResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetResponse) ProtoMessage() {}

func (x *ConfigGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetResponse.ProtoReflect.Descriptor instead.
func (*ConfigGetResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{30}
}

func (x *ConfigGetResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type ConfigSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSetRequest) Reset() {
	*x = ConfigSetRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSetRequest) ProtoMessage() {}

func (x *ConfigSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSetRequest.ProtoReflect.Descriptor instead.
func (*ConfigSetRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{31}
}

func (x *ConfigSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Network
type NetworkStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DhtEnabled    bool                   `protobuf:"varint,1,opt,name=dht_enabled,json=dhtEnabled,proto3" json:"dht_enabled,omitempty"`
	DhtPeers      int32                  `protobuf:"varint,2,opt,name=dht_peers,json=dhtPeers,proto3" json:"dht_peers,omitempty"`
	MdnsPeers     int32                  `protobuf:"varint,3,opt,name=mdns_peers,json=mdnsPeers,proto3" json:"mdns_peers,omitempty"`
	Online        bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStatusResponse) Reset() {
	*x = NetworkStatusResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatusResponse) ProtoMessage() {}

func (x *NetworkStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatusResponse.ProtoReflect.Descriptor instead.
func (*NetworkStatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{32}
}

func (x *NetworkStatusResponse) GetDhtEnabled() bool {
	if x != nil {
		return x.DhtEnabled
	}
	return false
}

func (x *NetworkStatusResponse) GetDhtPeers() int32 {
	if x != nil {
		return x.DhtPeers
	}
	return 0
}

func (x *NetworkStatusResponse) GetMdnsPeers() int32 {
	if x != nil {
		return x.MdnsPeers
	}
	return 0
}

func (x *NetworkStatusResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// Status
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	PeerCount     int32                  `protobuf:"varint,2,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	NetworkOnline bool                   `protobuf:"varint,3,opt,name=network_online,json=networkOnline,proto3" json:"network_online,omitempty"`
	Uptime        string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{33}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *StatusResponse) GetNetworkOnline() bool {
	if x != nil {
		return x.NetworkOnline
	}
	return false
}

func (x *StatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type FullStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StatusResponse        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Network       *NetworkStatusResponse `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Queue         *QueueResponse         `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	NowPlaying    *NowPlayingResponse    `protobuf:"bytes,4,opt,name=now_playing,json=nowPlaying,proto3" json:"now_playing,omitempty"`
	Playlists     []string               `protobuf:"bytes,5,rep,name=playlists,proto3" json:"playlists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullStateResponse) Reset() {
	*x = FullStateResponse{}
	mi := &file_rpc_proto_raag_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullStateResponse) ProtoMessage() {}

func (x *FullStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullStateResponse.ProtoReflect.Descriptor instead.
func (*FullStateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{34}
}

func (x *FullStateResponse) GetStatus() *StatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *FullStateResponse) GetNetwork() *NetworkStatusResponse {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *FullStateResponse) GetQueue() *QueueResponse {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *FullStateResponse) GetNowPlaying() *NowPlayingResponse {
	if x != nil {
		return x.NowPlaying
	}
	return nil
}

func (x *FullStateResponse) GetPlaylists() []string {
	if x != nil {
		return x.Playlists
	}
	return nil
}

// Transfer
type TransferEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	SongTitle     string                 `protobuf:"bytes,2,opt,name=song_title,json=songTitle,proto3" json:"song_title,omitempty"`
	DoneBlocks    int32                  `protobuf:"varint,3,opt,name=done_blocks,json=doneBlocks,proto3" json:"done_blocks,omitempty"`
	TotalBlocks   int32                  `protobuf:"varint,4,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferEvent) Reset() {
	*x = TransferEvent{}
	mi := &file_rpc_proto_raag_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferEvent) ProtoMessage() {}

func (x *TransferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferEvent.ProtoReflect.Descriptor instead.
func (*TransferEvent) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{35}
}

func (x *TransferEvent) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *TransferEvent) GetSongTitle() string {
	if x != nil {
		return x.SongTitle
	}
	return ""
}

func (x *TransferEvent) GetDoneBlocks() int32 {
	if x != nil {
		return x.DoneBlocks
	}
	return 0
}

func (x *TransferEvent) GetTotalBlocks() int32 {
	if x != nil {
		return x.TotalBlocks
	}
	return 0
}

func (x *TransferEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Sharing
type ShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareRequest) Reset() {
	*x = ShareRequest{}
	mi := &file_rpc_proto_raag_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareRequest) ProtoMessage() {}

func (x *ShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_raag_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareRequest.ProtoReflect.Descriptor instead.
func (*ShareRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_raag_proto_rawDescGZIP(), []int{36}
}

func (x *ShareRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_rpc_proto_raag_proto protoreflect.FileDescriptor

const file_rpc_proto_raag_proto_rawDesc = "" +
	"\n" +
	"\x14rpc/proto/raag.proto\x12\x04raag\"\a\n" +
	"\x05Empty\".\n" +
	"\x0eConnectRequest\x12\x1c\n" +
	"\tmultiaddr\x18\x01 \x01(\tR\tmultiaddr\",\n" +
	"\x11DisconnectRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"0\n" +
	"\x10BootstrapRequest\x12\x1c\n" +
	"\tmultiaddr\x18\x01 \x01(\tR\tmultiaddr\"\x0f\n" +
	"\rEmptyResponse\"L\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\bR\tconnected\"8\n" +
	"\x10PeerListResponse\x12$\n" +
	"\x05peers\x18\x01 \x03(\v2\x0e.raag.PeerInfoR\x05peers\"\xc9\x02\n" +
	"\x11PeersInfoResponse\x125\n" +
	"\x04self\x18\x01 \x03(\v2!.raag.PeersInfoResponse.SelfEntryR\x04self\x127\n" +
	"\x0fconnected_peers\x18\x02 \x03(\v2\x0e.raag.PeerInfoR\x0econnectedPeers\x120\n" +
	"\x14connected_peer_count\x18\x03 \x01(\x05R\x12connectedPeerCount\x12/\n" +
	"\vknown_peers\x18\x04 \x03(\v2\x0e.raag.PeerInfoR\n" +
	"knownPeers\x12(\n" +
	"\x10known_peer_count\x18\x05 \x01(\x05R\x0eknownPeerCount\x1a7\n" +
	"\tSelfEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x12KnownPeersResponse\x12$\n" +
	"\x05peers\x18\x01 \x03(\v2\x0e.raag.PeerInfoR\x05peers\"N\n" +
	"\tPeerEvent\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event\"w\n" +
	"\vLibrarySong\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x03 \x01(\tR\x05album\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x10\n" +
	"\x03cid\x18\x05 \x01(\tR\x03cid\">\n" +
	"\x13LibraryListResponse\x12'\n" +
	"\x05songs\x18\x01 \x03(\v2\x11.raag.LibrarySongR\x05songs\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"@\n" +
	"\x15LibrarySearchResponse\x12'\n" +
	"\x05songs\x18\x01 \x03(\v2\x11.raag.LibrarySongR\x05songs\" \n" +
	"\n" +
	"AddRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"#\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"Z\n" +
	"\x0eRescanResponse\x12\x18\n" +
	"\ascanned\x18\x01 \x01(\x05R\ascanned\x12\x14\n" +
	"\x05added\x18\x02 \x01(\x05R\x05added\x12\x18\n" +
	"\aremoved\x18\x03 \x01(\x05R\aremoved\"7\n" +
	"\vPlayRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\"'\n" +
	"\rVolumeRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\x05R\x06volume\")\n" +
	"\vSeekRequest\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\"]\n" +
	"\rQueueResponse\x12'\n" +
	"\x05queue\x18\x01 \x03(\v2\x11.raag.LibrarySongR\x05queue\x12#\n" +
	"\rcurrent_index\x18\x02 \x01(\x05R\fcurrentIndex\"\xa5\x01\n" +
	"\x12NowPlayingResponse\x12%\n" +
	"\x04song\x18\x01 \x01(\v2\x11.raag.LibrarySongR\x04song\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x18\n" +
	"\aplaying\x18\x04 \x01(\bR\aplaying\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x05R\x06volume\"\xd3\x01\n" +
	"\vPlayerEvent\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x03 \x01(\tR\x05album\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\x12\x18\n" +
	"\aplaying\x18\a \x01(\bR\aplaying\x12\x16\n" +
	"\x06paused\x18\b \x01(\bR\x06paused\"*\n" +
	"\x14PlaylistSongsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"@\n" +
	"\x15PlaylistSongsResponse\x12'\n" +
	"\x05songs\x18\x01 \x03(\v2\x11.raag.LibrarySongR\x05songs\"+\n" +
	"\x15PlaylistCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x15PlaylistDeleteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x14PlaylistListResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"E\n" +
	"\x12PlaylistAddRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tsong_path\x18\x02 \x01(\tR\bsongPath\"A\n" +
	"\x15PlaylistRemoveRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\"+\n" +
	"\x11ConfigGetResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\":\n" +
	"\x10ConfigSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x8c\x01\n" +
	"\x15NetworkStatusResponse\x12\x1f\n" +
	"\vdht_enabled\x18\x01 \x01(\bR\n" +
	"dhtEnabled\x12\x1b\n" +
	"\tdht_peers\x18\x02 \x01(\x05R\bdhtPeers\x12\x1d\n" +
	"\n" +
	"mdns_peers\x18\x03 \x01(\x05R\tmdnsPeers\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\"\xa2\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x02 \x01(\x05R\tpeerCount\x12%\n" +
	"\x0enetwork_online\x18\x03 \x01(\bR\rnetworkOnline\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\xfc\x01\n" +
	"\x11FullStateResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.raag.StatusResponseR\x06status\x125\n" +
	"\anetwork\x18\x02 \x01(\v2\x1b.raag.NetworkStatusResponseR\anetwork\x12)\n" +
	"\x05queue\x18\x03 \x01(\v2\x13.raag.QueueResponseR\x05queue\x129\n" +
	"\vnow_playing\x18\x04 \x01(\v2\x18.raag.NowPlayingResponseR\n" +
	"nowPlaying\x12\x1c\n" +
	"\tplaylists\x18\x05 \x03(\tR\tplaylists\"\x9c\x01\n" +
	"\rTransferEvent\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x1d\n" +
	"\n" +
	"song_title\x18\x02 \x01(\tR\tsongTitle\x12\x1f\n" +
	"\vdone_blocks\x18\x03 \x01(\x05R\n" +
	"doneBlocks\x12!\n" +
	"\ftotal_blocks\x18\x04 \x01(\x05R\vtotalBlocks\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\"\n" +
	"\fShareRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path2\xda\x0e\n" +
	"\x04Raag\x120\n" +
	"\tPeersList\x12\v.raag.Empty\x1a\x16.raag.PeerListResponse\x121\n" +
	"\tPeersInfo\x12\v.raag.Empty\x1a\x17.raag.PeersInfoResponse\x12,\n" +
	"\aConnect\x12\x14.raag.ConnectRequest\x1a\v.raag.Empty\x122\n" +
	"\n" +
	"Disconnect\x12\x17.raag.DisconnectRequest\x1a\v.raag.Empty\x123\n" +
	"\fAddBootstrap\x12\x16.raag.BootstrapRequest\x1a\v.raag.Empty\x123\n" +
	"\n" +
	"KnownPeers\x12\v.raag.Empty\x1a\x18.raag.KnownPeersResponse\x125\n" +
	"\vLibraryList\x12\v.raag.Empty\x1a\x19.raag.LibraryListResponse\x12A\n" +
	"\rLibrarySearch\x12\x13.raag.SearchRequest\x1a\x1b.raag.LibrarySearchResponse\x12+\n" +
	"\n" +
	"LibraryAdd\x12\x10.raag.AddRequest\x1a\v.raag.Empty\x121\n" +
	"\rLibraryRemove\x12\x13.raag.RemoveRequest\x1a\v.raag.Empty\x122\n" +
	"\rLibraryRescan\x12\v.raag.Empty\x1a\x14.raag.RescanResponse\x12&\n" +
	"\x04Play\x12\x11.raag.PlayRequest\x1a\v.raag.Empty\x12!\n" +
	"\x05Pause\x12\v.raag.Empty\x1a\v.raag.Empty\x12\"\n" +
	"\x06Resume\x12\v.raag.Empty\x1a\v.raag.Empty\x12 \n" +
	"\x04Stop\x12\v.raag.Empty\x1a\v.raag.Empty\x12 \n" +
	"\x04Next\x12\v.raag.Empty\x1a\v.raag.Empty\x12$\n" +
	"\bPrevious\x12\v.raag.Empty\x1a\v.raag.Empty\x12-\n" +
	"\tSetVolume\x12\x13.raag.VolumeRequest\x1a\v.raag.Empty\x12&\n" +
	"\x04Seek\x12\x11.raag.SeekRequest\x1a\v.raag.Empty\x12,\n" +
	"\bGetQueue\x12\v.raag.Empty\x1a\x13.raag.QueueResponse\x123\n" +
	"\n" +
	"NowPlaying\x12\v.raag.Empty\x1a\x18.raag.NowPlayingResponse\x12H\n" +
	"\rPlaylistSongs\x12\x1a.raag.PlaylistSongsRequest\x1a\x1b.raag.PlaylistSongsResponse\x12:\n" +
	"\x0ePlaylistCreate\x12\x1b.raag.PlaylistCreateRequest\x1a\v.raag.Empty\x12:\n" +
	"\x0ePlaylistDelete\x12\x1b.raag.PlaylistDeleteRequest\x1a\v.raag.Empty\x127\n" +
	"\fPlaylistList\x12\v.raag.Empty\x1a\x1a.raag.PlaylistListResponse\x124\n" +
	"\vPlaylistAdd\x12\x18.raag.PlaylistAddRequest\x1a\v.raag.Empty\x12:\n" +
	"\x0ePlaylistRemove\x12\x1b.raag.PlaylistRemoveRequest\x1a\v.raag.Empty\x121\n" +
	"\tConfigGet\x12\v.raag.Empty\x1a\x17.raag.ConfigGetResponse\x120\n" +
	"\tConfigSet\x12\x16.raag.ConfigSetRequest\x1a\v.raag.Empty\x12'\n" +
	"\vConfigReset\x12\v.raag.Empty\x1a\v.raag.Empty\x129\n" +
	"\rNetworkStatus\x12\v.raag.Empty\x1a\x1b.raag.NetworkStatusResponse\x12+\n" +
	"\x06Status\x12\v.raag.Empty\x1a\x14.raag.StatusResponse\x124\n" +
	"\fGetFullState\x12\v.raag.Empty\x1a\x17.raag.FullStateResponse\x12$\n" +
	"\bShutdown\x12\v.raag.Empty\x1a\v.raag.Empty\x12,\n" +
	"\tShareSong\x12\x12.raag.ShareRequest\x1a\v.raag.Empty\x12/\n" +
	"\vWatchPlayer\x12\v.raag.Empty\x1a\x11.raag.PlayerEvent0\x01\x12,\n" +
	"\n" +
	"WatchPeers\x12\v.raag.Empty\x1a\x0f.raag.PeerEvent0\x01\x124\n" +
	"\x0eWatchTransfers\x12\v.raag.Empty\x1a\x13.raag.TransferEvent0\x01B%Z#github.com/p-society/raag/rpc/protob\x06proto3"

var (
	file_rpc_proto_raag_proto_rawDescOnce sync.Once
	file_rpc_proto_raag_proto_rawDescData []byte
)

func file_rpc_proto_raag_proto_rawDescGZIP() []byte {
	file_rpc_proto_raag_proto_rawDescOnce.Do(func() {
		file_rpc_proto_raag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_raag_proto_rawDesc), len(file_rpc_proto_raag_proto_rawDesc)))
	})
	return file_rpc_proto_raag_proto_rawDescData
}

var file_rpc_proto_raag_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_rpc_proto_raag_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: raag.Empty
	(*ConnectRequest)(nil),        // 1: raag.ConnectRequest
	(*DisconnectRequest)(nil),     // 2: raag.DisconnectRequest
	(*BootstrapRequest)(nil),      // 3: raag.BootstrapRequest
	(*EmptyResponse)(nil),         // 4: raag.EmptyResponse
	(*PeerInfo)(nil),              // 5: raag.PeerInfo
	(*PeerListResponse)(nil),      // 6: raag.PeerListResponse
	(*PeersInfoResponse)(nil),     // 7: raag.PeersInfoResponse
	(*KnownPeersResponse)(nil),    // 8: raag.KnownPeersResponse
	(*PeerEvent)(nil),             // 9: raag.PeerEvent
	(*LibrarySong)(nil),           // 10: raag.LibrarySong
	(*LibraryListResponse)(nil),   // 11: raag.LibraryListResponse
	(*SearchRequest)(nil),         // 12: raag.SearchRequest
	(*LibrarySearchResponse)(nil), // 13: raag.LibrarySearchResponse
	(*AddRequest)(nil),            // 14: raag.AddRequest
	(*RemoveRequest)(nil),         // 15: raag.RemoveRequest
	(*RescanResponse)(nil),        // 16: raag.RescanResponse
	(*PlayRequest)(nil),           // 17: raag.PlayRequest
	(*VolumeRequest)(nil),         // 18: raag.VolumeRequest
	(*SeekRequest)(nil),           // 19: raag.SeekRequest
	(*QueueResponse)(nil),         // 20: raag.QueueResponse
	(*NowPlayingResponse)(nil),    // 21: raag.NowPlayingResponse
	(*PlayerEvent)(nil),           // 22: raag.PlayerEvent
	(*PlaylistSongsRequest)(nil),  // 23: raag.PlaylistSongsRequest
	(*PlaylistSongsResponse)(nil), // 24: raag.PlaylistSongsResponse
	(*PlaylistCreateRequest)(nil), // 25: raag.PlaylistCreateRequest
	(*PlaylistDeleteRequest)(nil), // 26: raag.PlaylistDeleteRequest
	(*PlaylistListResponse)(nil),  // 27: raag.PlaylistListResponse
	(*PlaylistAddRequest)(nil),    // 28: raag.PlaylistAddRequest
	(*PlaylistRemoveRequest)(nil), // 29: raag.PlaylistRemoveRequest
	(*ConfigGetResponse)(nil),     // 30: raag.ConfigGetResponse
	(*ConfigSetRequest)(nil),      // 31: raag.ConfigSetRequest
	(*NetworkStatusResponse)(nil), // 32: raag.NetworkStatusResponse
	(*StatusResponse)(nil),        // 33: raag.StatusResponse
	(*FullStateResponse)(nil),     // 34: raag.FullStateResponse
	(*TransferEvent)(nil),         // 35: raag.TransferEvent
	(*ShareRequest)(nil),          // 36: raag.ShareRequest
	nil,                           // 37: raag.PeersInfoResponse.SelfEntry
}
var file_rpc_proto_raag_proto_depIdxs = []int32{
	5,  // 0: raag.PeerListResponse.peers:type_name -> raag.PeerInfo
	37, // 1: raag.PeersInfoResponse.self:type_name -> raag.PeersInfoResponse.SelfEntry
	5,  // 2: raag.PeersInfoResponse.connected_peers:type_name -> raag.PeerInfo
	5,  // 3: raag.PeersInfoResponse.known_peers:type_name -> raag.PeerInfo
	5,  // 4: raag.KnownPeersResponse.peers:type_name -> raag.PeerInfo
	10, // 5: raag.LibraryListResponse.songs:type_name -> raag.LibrarySong
	10, // 6: raag.LibrarySearchResponse.songs:type_name -> raag.LibrarySong
	10, // 7: raag.QueueResponse.queue:type_name -> raag.LibrarySong
	10, // 8: raag.NowPlayingResponse.song:type_name -> raag.LibrarySong
	10, // 9: raag.PlaylistSongsResponse.songs:type_name -> raag.LibrarySong
	33, // 10: raag.FullStateResponse.status:type_name -> raag.StatusResponse
	32, // 11: raag.FullStateResponse.network:type_name -> raag.NetworkStatusResponse
	20, // 12: raag.FullStateResponse.queue:type_name -> raag.QueueResponse
	21, // 13: raag.FullStateResponse.now_playing:type_name -> raag.NowPlayingResponse
	0,  // 14: raag.Raag.PeersList:input_type -> raag.Empty
	0,  // 15: raag.Raag.PeersInfo:input_type -> raag.Empty
	1,  // 16: raag.Raag.Connect:input_type -> raag.ConnectRequest
	2,  // 17: raag.Raag.Disconnect:input_type -> raag.DisconnectRequest
	3,  // 18: raag.Raag.AddBootstrap:input_type -> raag.BootstrapRequest
	0,  // 19: raag.Raag.KnownPeers:input_type -> raag.Empty
	0,  // 20: raag.Raag.LibraryList:input_type -> raag.Empty
	12, // 21: raag.Raag.LibrarySearch:input_type -> raag.SearchRequest
	14, // 22: raag.Raag.LibraryAdd:input_type -> raag.AddRequest
	15, // 23: raag.Raag.LibraryRemove:input_type -> raag.RemoveRequest
	0,  // 24: raag.Raag.LibraryRescan:input_type -> raag.Empty
	17, // 25: raag.Raag.Play:input_type -> raag.PlayRequest
	0,  // 26: raag.Raag.Pause:input_type -> raag.Empty
	0,  // 27: raag.Raag.Resume:input_type -> raag.Empty
	0,  // 28: raag.Raag.Stop:input_type -> raag.Empty
	0,  // 29: raag.Raag.Next:input_type -> raag.Empty
	0,  // 30: raag.Raag.Previous:input_type -> raag.Empty
	18, // 31: raag.Raag.SetVolume:input_type -> raag.VolumeRequest
	19, // 32: raag.Raag.Seek:input_type -> raag.SeekRequest
	0,  // 33: raag.Raag.GetQueue:input_type -> raag.Empty
	0,  // 34: raag.Raag.NowPlaying:input_type -> raag.Empty
	23, // 35: raag.Raag.PlaylistSongs:input_type -> raag.PlaylistSongsRequest
	25, // 36: raag.Raag.PlaylistCreate:input_type -> raag.PlaylistCreateRequest
	26, // 37: raag.Raag.PlaylistDelete:input_type -> raag.PlaylistDeleteRequest
	0,  // 38: raag.Raag.PlaylistList:input_type -> raag.Empty
	28, // 39: raag.Raag.PlaylistAdd:input_type -> raag.PlaylistAddRequest
	29, // 40: raag.Raag.PlaylistRemove:input_type -> raag.PlaylistRemoveRequest
	0,  // 41: raag.Raag.ConfigGet:input_type -> raag.Empty
	31, // 42: raag.Raag.ConfigSet:input_type -> raag.ConfigSetRequest
	0,  // 43: raag.Raag.ConfigReset:input_type -> raag.Empty
	0,  // 44: raag.Raag.NetworkStatus:input_type -> raag.Empty
	0,  // 45: raag.Raag.Status:input_type -> raag.Empty
	0,  // 46: raag.Raag.GetFullState:input_type -> raag.Empty
	0,  // 47: raag.Raag.Shutdown:input_type -> raag.Empty
	36, // 48: raag.Raag.ShareSong:input_type -> raag.ShareRequest
	0,  // 49: raag.Raag.WatchPlayer:input_type -> raag.Empty
	0,  // 50: raag.Raag.WatchPeers:input_type -> raag.Empty
	0,  // 51: raag.Raag.WatchTransfers:input_type -> raag.Empty
	6,  // 52: raag.Raag.PeersList:output_type -> raag.PeerListResponse
	7,  // 53: raag.Raag.PeersInfo:output_type -> raag.PeersInfoResponse
	0,  // 54: raag.Raag.Connect:output_type -> raag.Empty
	0,  // 55: raag.Raag.Disconnect:output_type -> raag.Empty
	0,  // 56: raag.Raag.AddBootstrap:output_type -> raag.Empty
	8,  // 57: raag.Raag.KnownPeers:output_type -> raag.KnownPeersResponse
	11, // 58: raag.Raag.LibraryList:output_type -> raag.LibraryListResponse
	13, // 59: raag.Raag.LibrarySearch:output_type -> raag.LibrarySearchResponse
	0,  // 60: raag.Raag.LibraryAdd:output_type -> raag.Empty
	0,  // 61: raag.Raag.LibraryRemove:output_type -> raag.Empty
	16, // 62: raag.Raag.LibraryRescan:output_type -> raag.RescanResponse
	0,  // 63: raag.Raag.Play:output_type -> raag.Empty
	0,  // 64: raag.Raag.Pause:output_type -> raag.Empty
	0,  // 65: raag.Raag.Resume:output_type -> raag.Empty
	0,  // 66: raag.Raag.Stop:output_type -> raag.Empty
	0,  // 67: raag.Raag.Next:output_type -> raag.Empty
	0,  // 68: raag.Raag.Previous:output_type -> raag.Empty
	0,  // 69: raag.Raag.SetVolume:output_type -> raag.Empty
	0,  // 70: raag.Raag.Seek:output_type -> raag.Empty
	20, // 71: raag.Raag.GetQueue:output_type -> raag.QueueResponse
	21, // 72: raag.Raag.NowPlaying:output_type -> raag.NowPlayingResponse
	24, // 73: raag.Raag.PlaylistSongs:output_type -> raag.PlaylistSongsResponse
	0,  // 74: raag.Raag.PlaylistCreate:output_type -> raag.Empty
	0,  // 75: raag.Raag.PlaylistDelete:output_type -> raag.Empty
	27, // 76: raag.Raag.PlaylistList:output_type -> raag.PlaylistListResponse
	0,  // 77: raag.Raag.PlaylistAdd:output_type -> raag.Empty
	0,  // 78: raag.Raag.PlaylistRemove:output_type -> raag.Empty
	30, // 79: raag.Raag.ConfigGet:output_type -> raag.ConfigGetResponse
	0,  // 80: raag.Raag.ConfigSet:output_type -> raag.Empty
	0,  // 81: raag.Raag.ConfigReset:output_type -> raag.Empty
	32, // 82: raag.Raag.NetworkStatus:output_type -> raag.NetworkStatusResponse
	33, // 83: raag.Raag.Status:output_type -> raag.StatusResponse
	34, // 84: raag.Raag.GetFullState:output_type -> raag.FullStateResponse
	0,  // 85: raag.Raag.Shutdown:output_type -> raag.Empty
	0,  // 86: raag.Raag.ShareSong:output_type -> raag.Empty
	22, // 87: raag.Raag.WatchPlayer:output_type -> raag.PlayerEvent
	9,  // 88: raag.Raag.WatchPeers:output_type -> raag.PeerEvent
	35, // 89: raag.Raag.WatchTransfers:output_type -> raag.TransferEvent
	52, // [52:90] is the sub-list for method output_type
	14, // [14:52] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_rpc_proto_raag_proto_init() }
func file_rpc_proto_raag_proto_init() {
	if File_rpc_proto_raag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_raag_proto_rawDesc), len(file_rpc_proto_raag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_raag_proto_goTypes,
		DependencyIndexes: file_rpc_proto_raag_proto_depIdxs,
		MessageInfos:      file_rpc_proto_raag_proto_msgTypes,
	}.Build()
	File_rpc_proto_raag_proto = out.File
	file_rpc_proto_raag_proto_goTypes = nil
	file_rpc_proto_raag_proto_depIdxs = nil
}
