// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: rpc/proto/raag.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Raag_PeersList_FullMethodName      = "/raag.Raag/PeersList"
	Raag_PeersInfo_FullMethodName      = "/raag.Raag/PeersInfo"
	Raag_Connect_FullMethodName        = "/raag.Raag/Connect"
	Raag_Disconnect_FullMethodName     = "/raag.Raag/Disconnect"
	Raag_AddBootstrap_FullMethodName   = "/raag.Raag/AddBootstrap"
	Raag_KnownPeers_FullMethodName     = "/raag.Raag/KnownPeers"
	Raag_LibraryList_FullMethodName    = "/raag.Raag/LibraryList"
	Raag_LibrarySearch_FullMethodName  = "/raag.Raag/LibrarySearch"
	Raag_LibraryAdd_FullMethodName     = "/raag.Raag/LibraryAdd"
	Raag_LibraryRemove_FullMethodName  = "/raag.Raag/LibraryRemove"
	Raag_LibraryRescan_FullMethodName  = "/raag.Raag/LibraryRescan"
	Raag_Play_FullMethodName           = "/raag.Raag/Play"
	Raag_Pause_FullMethodName          = "/raag.Raag/Pause"
	Raag_Resume_FullMethodName         = "/raag.Raag/Resume"
	Raag_Stop_FullMethodName           = "/raag.Raag/Stop"
	Raag_Next_FullMethodName           = "/raag.Raag/Next"
	Raag_Previous_FullMethodName       = "/raag.Raag/Previous"
	Raag_SetVolume_FullMethodName      = "/raag.Raag/SetVolume"
	Raag_Seek_FullMethodName           = "/raag.Raag/Seek"
	Raag_GetQueue_FullMethodName       = "/raag.Raag/GetQueue"
	Raag_NowPlaying_FullMethodName     = "/raag.Raag/NowPlaying"
	Raag_PlaylistSongs_FullMethodName  = "/raag.Raag/PlaylistSongs"
	Raag_PlaylistCreate_FullMethodName = "/raag.Raag/PlaylistCreate"
	Raag_PlaylistDelete_FullMethodName = "/raag.Raag/PlaylistDelete"
	Raag_PlaylistList_FullMethodName   = "/raag.Raag/PlaylistList"
	Raag_PlaylistAdd_FullMethodName    = "/raag.Raag/PlaylistAdd"
	Raag_PlaylistRemove_FullMethodName = "/raag.Raag/PlaylistRemove"
	Raag_ConfigGet_FullMethodName      = "/raag.Raag/ConfigGet"
	Raag_ConfigSet_FullMethodName      = "/raag.Raag/ConfigSet"
	Raag_ConfigReset_FullMethodName    = "/raag.Raag/ConfigReset"
	Raag_NetworkStatus_FullMethodName  = "/raag.Raag/NetworkStatus"
	Raag_Status_FullMethodName         = "/raag.Raag/Status"
	Raag_GetFullState_FullMethodName   = "/raag.Raag/GetFullState"
	Raag_Shutdown_FullMethodName       = "/raag.Raag/Shutdown"
	Raag_ShareSong_FullMethodName      = "/raag.Raag/ShareSong"
	Raag_WatchPlayer_FullMethodName    = "/raag.Raag/WatchPlayer"
	Raag_WatchPeers_FullMethodName     = "/raag.Raag/WatchPeers"
	Raag_WatchTransfers_FullMethodName = "/raag.Raag/WatchTransfers"
)

// RaagClient is the client API for Raag service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaagClient interface {
	// Peer Management
	PeersList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerListResponse, error)
	PeersInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeersInfoResponse, error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*Empty, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*Empty, error)
	AddBootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*Empty, error)
	KnownPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KnownPeersResponse, error)
	// Library
	LibraryList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LibraryListResponse, error)
	LibrarySearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*LibrarySearchResponse, error)
	LibraryAdd(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Empty, error)
	LibraryRemove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*Empty, error)
	LibraryRescan(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RescanResponse, error)
	// Player
	Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*Empty, error)
	Pause(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Resume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Next(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Previous(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	SetVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Empty, error)
	Seek(ctx context.Context, in *SeekRequest, opts ...grpc.CallOption) (*Empty, error)
	GetQueue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QueueResponse, error)
	NowPlaying(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NowPlayingResponse, error)
	// Playlist
	PlaylistSongs(ctx context.Context, in *PlaylistSongsRequest, opts ...grpc.CallOption) (*PlaylistSongsResponse, error)
	PlaylistCreate(ctx context.Context, in *PlaylistCreateRequest, opts ...grpc.CallOption) (*Empty, error)
	PlaylistDelete(ctx context.Context, in *PlaylistDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	PlaylistList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PlaylistListResponse, error)
	PlaylistAdd(ctx context.Context, in *PlaylistAddRequest, opts ...grpc.CallOption) (*Empty, error)
	PlaylistRemove(ctx context.Context, in *PlaylistRemoveRequest, opts ...grpc.CallOption) (*Empty, error)
	// Config
	ConfigGet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigGetResponse, error)
	ConfigSet(ctx context.Context, in *ConfigSetRequest, opts ...grpc.CallOption) (*Empty, error)
	ConfigReset(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Network
	NetworkStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkStatusResponse, error)
	// Status
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	GetFullState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FullStateResponse, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Sharing
	ShareSong(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Empty, error)
	// Server-streaming RPCs (TUI live updates)
	WatchPlayer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlayerEvent], error)
	WatchPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerEvent], error)
	WatchTransfers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferEvent], error)
}

type raagClient struct {
	cc grpc.ClientConnInterface
}

func NewRaagClient(cc grpc.ClientConnInterface) RaagClient {
	return &raagClient{cc}
}

func (c *raagClient) PeersList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerListResponse)
	err := c.cc.Invoke(ctx, Raag_PeersList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) PeersInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeersInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeersInfoResponse)
	err := c.cc.Invoke(ctx, Raag_PeersInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) AddBootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_AddBootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) KnownPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KnownPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnownPeersResponse)
	err := c.cc.Invoke(ctx, Raag_KnownPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) LibraryList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LibraryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LibraryListResponse)
	err := c.cc.Invoke(ctx, Raag_LibraryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) LibrarySearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*LibrarySearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LibrarySearchResponse)
	err := c.cc.Invoke(ctx, Raag_LibrarySearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) LibraryAdd(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_LibraryAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) LibraryRemove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_LibraryRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) LibraryRescan(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RescanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescanResponse)
	err := c.cc.Invoke(ctx, Raag_LibraryRescan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_Play_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) Pause(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) Resume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) Next(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_Next_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) Previous(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_Previous_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) SetVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_SetVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) Seek(ctx context.Context, in *SeekRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_Seek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) GetQueue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueResponse)
	err := c.cc.Invoke(ctx, Raag_GetQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) NowPlaying(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NowPlayingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NowPlayingResponse)
	err := c.cc.Invoke(ctx, Raag_NowPlaying_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) PlaylistSongs(ctx context.Context, in *PlaylistSongsRequest, opts ...grpc.CallOption) (*PlaylistSongsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaylistSongsResponse)
	err := c.cc.Invoke(ctx, Raag_PlaylistSongs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) PlaylistCreate(ctx context.Context, in *PlaylistCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_PlaylistCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) PlaylistDelete(ctx context.Context, in *PlaylistDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_PlaylistDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) PlaylistList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PlaylistListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaylistListResponse)
	err := c.cc.Invoke(ctx, Raag_PlaylistList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) PlaylistAdd(ctx context.Context, in *PlaylistAddRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_PlaylistAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) PlaylistRemove(ctx context.Context, in *PlaylistRemoveRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_PlaylistRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) ConfigGet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigGetResponse)
	err := c.cc.Invoke(ctx, Raag_ConfigGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) ConfigSet(ctx context.Context, in *ConfigSetRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_ConfigSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) ConfigReset(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_ConfigReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) NetworkStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkStatusResponse)
	err := c.cc.Invoke(ctx, Raag_NetworkStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Raag_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) GetFullState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FullStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FullStateResponse)
	err := c.cc.Invoke(ctx, Raag_GetFullState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) ShareSong(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Raag_ShareSong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raagClient) WatchPlayer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlayerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Raag_ServiceDesc.Streams[0], Raag_WatchPlayer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, PlayerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Raag_WatchPlayerClient = grpc.ServerStreamingClient[PlayerEvent]

func (c *raagClient) WatchPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Raag_ServiceDesc.Streams[1], Raag_WatchPeers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, PeerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Raag_WatchPeersClient = grpc.ServerStreamingClient[PeerEvent]

func (c *raagClient) WatchTransfers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Raag_ServiceDesc.Streams[2], Raag_WatchTransfers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, TransferEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Raag_WatchTransfersClient = grpc.ServerStreamingClient[TransferEvent]

// RaagServer is the server API for Raag service.
// All implementations must embed UnimplementedRaagServer
// for forward compatibility.
type RaagServer interface {
	// Peer Management
	PeersList(context.Context, *Empty) (*PeerListResponse, error)
	PeersInfo(context.Context, *Empty) (*PeersInfoResponse, error)
	Connect(context.Context, *ConnectRequest) (*Empty, error)
	Disconnect(context.Context, *DisconnectRequest) (*Empty, error)
	AddBootstrap(context.Context, *BootstrapRequest) (*Empty, error)
	KnownPeers(context.Context, *Empty) (*KnownPeersResponse, error)
	// Library
	LibraryList(context.Context, *Empty) (*LibraryListResponse, error)
	LibrarySearch(context.Context, *SearchRequest) (*LibrarySearchResponse, error)
	LibraryAdd(context.Context, *AddRequest) (*Empty, error)
	LibraryRemove(context.Context, *RemoveRequest) (*Empty, error)
	LibraryRescan(context.Context, *Empty) (*RescanResponse, error)
	// Player
	Play(context.Context, *PlayRequest) (*Empty, error)
	Pause(context.Context, *Empty) (*Empty, error)
	Resume(context.Context, *Empty) (*Empty, error)
	Stop(context.Context, *Empty) (*Empty, error)
	Next(context.Context, *Empty) (*Empty, error)
	Previous(context.Context, *Empty) (*Empty, error)
	SetVolume(context.Context, *VolumeRequest) (*Empty, error)
	Seek(context.Context, *SeekRequest) (*Empty, error)
	GetQueue(context.Context, *Empty) (*QueueResponse, error)
	NowPlaying(context.Context, *Empty) (*NowPlayingResponse, error)
	// Playlist
	PlaylistSongs(context.Context, *PlaylistSongsRequest) (*PlaylistSongsResponse, error)
	PlaylistCreate(context.Context, *PlaylistCreateRequest) (*Empty, error)
	PlaylistDelete(context.Context, *PlaylistDeleteRequest) (*Empty, error)
	PlaylistList(context.Context, *Empty) (*PlaylistListResponse, error)
	PlaylistAdd(context.Context, *PlaylistAddRequest) (*Empty, error)
	PlaylistRemove(context.Context, *PlaylistRemoveRequest) (*Empty, error)
	// Config
	ConfigGet(context.Context, *Empty) (*ConfigGetResponse, error)
	ConfigSet(context.Context, *ConfigSetRequest) (*Empty, error)
	ConfigReset(context.Context, *Empty) (*Empty, error)
	// Network
	NetworkStatus(context.Context, *Empty) (*NetworkStatusResponse, error)
	// Status
	Status(context.Context, *Empty) (*StatusResponse, error)
	GetFullState(context.Context, *Empty) (*FullStateResponse, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	// Sharing
	ShareSong(context.Context, *ShareRequest) (*Empty, error)
	// Server-streaming RPCs (TUI live updates)
	WatchPlayer(*Empty, grpc.ServerStreamingServer[PlayerEvent]) error
	WatchPeers(*Empty, grpc.ServerStreamingServer[PeerEvent]) error
	WatchTransfers(*Empty, grpc.ServerStreamingServer[TransferEvent]) error
	mustEmbedUnimplementedRaagServer()
}

// UnimplementedRaagServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaagServer struct{}

func (UnimplementedRaagServer) PeersList(context.Context, *Empty) (*PeerListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PeersList not implemented")
}
func (UnimplementedRaagServer) PeersInfo(context.Context, *Empty) (*PeersInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PeersInfo not implemented")
}
func (UnimplementedRaagServer) Connect(context.Context, *ConnectRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRaagServer) Disconnect(context.Context, *DisconnectRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedRaagServer) AddBootstrap(context.Context, *BootstrapRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBootstrap not implemented")
}
func (UnimplementedRaagServer) KnownPeers(context.Context, *Empty) (*KnownPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KnownPeers not implemented")
}
func (UnimplementedRaagServer) LibraryList(context.Context, *Empty) (*LibraryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LibraryList not implemented")
}
func (UnimplementedRaagServer) LibrarySearch(context.Context, *SearchRequest) (*LibrarySearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LibrarySearch not implemented")
}
func (UnimplementedRaagServer) LibraryAdd(context.Context, *AddRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LibraryAdd not implemented")
}
func (UnimplementedRaagServer) LibraryRemove(context.Context, *RemoveRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LibraryRemove not implemented")
}
func (UnimplementedRaagServer) LibraryRescan(context.Context, *Empty) (*RescanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LibraryRescan not implemented")
}
func (UnimplementedRaagServer) Play(context.Context, *PlayRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Play not implemented")
}
func (UnimplementedRaagServer) Pause(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedRaagServer) Resume(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedRaagServer) Stop(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedRaagServer) Next(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedRaagServer) Previous(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Previous not implemented")
}
func (UnimplementedRaagServer) SetVolume(context.Context, *VolumeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetVolume not implemented")
}
func (UnimplementedRaagServer) Seek(context.Context, *SeekRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Seek not implemented")
}
func (UnimplementedRaagServer) GetQueue(context.Context, *Empty) (*QueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueue not implemented")
}
func (UnimplementedRaagServer) NowPlaying(context.Context, *Empty) (*NowPlayingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NowPlaying not implemented")
}
func (UnimplementedRaagServer) PlaylistSongs(context.Context, *PlaylistSongsRequest) (*PlaylistSongsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaylistSongs not implemented")
}
func (UnimplementedRaagServer) PlaylistCreate(context.Context, *PlaylistCreateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaylistCreate not implemented")
}
func (UnimplementedRaagServer) PlaylistDelete(context.Context, *PlaylistDeleteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaylistDelete not implemented")
}
func (UnimplementedRaagServer) PlaylistList(context.Context, *Empty) (*PlaylistListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaylistList not implemented")
}
func (UnimplementedRaagServer) PlaylistAdd(context.Context, *PlaylistAddRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaylistAdd not implemented")
}
func (UnimplementedRaagServer) PlaylistRemove(context.Context, *PlaylistRemoveRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaylistRemove not implemented")
}
func (UnimplementedRaagServer) ConfigGet(context.Context, *Empty) (*ConfigGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigGet not implemented")
}
func (UnimplementedRaagServer) ConfigSet(context.Context, *ConfigSetRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigSet not implemented")
}
func (UnimplementedRaagServer) ConfigReset(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigReset not implemented")
}
func (UnimplementedRaagServer) NetworkStatus(context.Context, *Empty) (*NetworkStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NetworkStatus not implemented")
}
func (UnimplementedRaagServer) Status(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedRaagServer) GetFullState(context.Context, *Empty) (*FullStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFullState not implemented")
}
func (UnimplementedRaagServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedRaagServer) ShareSong(context.Context, *ShareRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareSong not implemented")
}
func (UnimplementedRaagServer) WatchPlayer(*Empty, grpc.ServerStreamingServer[PlayerEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchPlayer not implemented")
}
func (UnimplementedRaagServer) WatchPeers(*Empty, grpc.ServerStreamingServer[PeerEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchPeers not implemented")
}
func (UnimplementedRaagServer) WatchTransfers(*Empty, grpc.ServerStreamingServer[TransferEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchTransfers not implemented")
}
func (UnimplementedRaagServer) mustEmbedUnimplementedRaagServer() {}
func (UnimplementedRaagServer) testEmbeddedByValue()              {}

// UnsafeRaagServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaagServer will
// result in compilation errors.
type UnsafeRaagServer interface {
	mustEmbedUnimplementedRaagServer()
}

func RegisterRaagServer(s grpc.ServiceRegistrar, srv RaagServer) {
	// If the following call panics, it indicates UnimplementedRaagServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Raag_ServiceDesc, srv)
}

func _Raag_PeersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).PeersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_PeersList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).PeersList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_PeersInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).PeersInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_PeersInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).PeersInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_AddBootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).AddBootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_AddBootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).AddBootstrap(ctx, req.(*BootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_KnownPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).KnownPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_KnownPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).KnownPeers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_LibraryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).LibraryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_LibraryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).LibraryList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_LibrarySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).LibrarySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_LibrarySearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).LibrarySearch(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_LibraryAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).LibraryAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_LibraryAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).LibraryAdd(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_LibraryRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).LibraryRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_LibraryRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).LibraryRemove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_LibraryRescan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).LibraryRescan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_LibraryRescan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).LibraryRescan(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_Play_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).Play(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_Play_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).Play(ctx, req.(*PlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).Pause(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).Resume(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_Next_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).Next(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_Previous_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).Previous(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_Previous_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).Previous(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_SetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).SetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_SetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).SetVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_Seek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).Seek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_Seek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).Seek(ctx, req.(*SeekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_GetQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).GetQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_GetQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).GetQueue(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_NowPlaying_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).NowPlaying(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_NowPlaying_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).NowPlaying(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_PlaylistSongs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaylistSongsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).PlaylistSongs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_PlaylistSongs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).PlaylistSongs(ctx, req.(*PlaylistSongsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_PlaylistCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaylistCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).PlaylistCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_PlaylistCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).PlaylistCreate(ctx, req.(*PlaylistCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_PlaylistDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaylistDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).PlaylistDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_PlaylistDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).PlaylistDelete(ctx, req.(*PlaylistDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_PlaylistList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).PlaylistList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_PlaylistList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).PlaylistList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_PlaylistAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaylistAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).PlaylistAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_PlaylistAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).PlaylistAdd(ctx, req.(*PlaylistAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_PlaylistRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaylistRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).PlaylistRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_PlaylistRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).PlaylistRemove(ctx, req.(*PlaylistRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_ConfigGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).ConfigGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_ConfigGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).ConfigGet(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_ConfigSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).ConfigSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_ConfigSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).ConfigSet(ctx, req.(*ConfigSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_ConfigReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).ConfigReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_ConfigReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).ConfigReset(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_NetworkStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).NetworkStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_NetworkStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).NetworkStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_GetFullState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).GetFullState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_GetFullState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).GetFullState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_ShareSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaagServer).ShareSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raag_ShareSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaagServer).ShareSong(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raag_WatchPlayer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RaagServer).WatchPlayer(m, &grpc.GenericServerStream[Empty, PlayerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Raag_WatchPlayerServer = grpc.ServerStreamingServer[PlayerEvent]

func _Raag_WatchPeers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RaagServer).WatchPeers(m, &grpc.GenericServerStream[Empty, PeerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Raag_WatchPeersServer = grpc.ServerStreamingServer[PeerEvent]

func _Raag_WatchTransfers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RaagServer).WatchTransfers(m, &grpc.GenericServerStream[Empty, TransferEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Raag_WatchTransfersServer = grpc.ServerStreamingServer[TransferEvent]

// Raag_ServiceDesc is the grpc.ServiceDesc for Raag service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Raag_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raag.Raag",
	HandlerType: (*RaagServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PeersList",
			Handler:    _Raag_PeersList_Handler,
		},
		{
			MethodName: "PeersInfo",
			Handler:    _Raag_PeersInfo_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _Raag_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Raag_Disconnect_Handler,
		},
		{
			MethodName: "AddBootstrap",
			Handler:    _Raag_AddBootstrap_Handler,
		},
		{
			MethodName: "KnownPeers",
			Handler:    _Raag_KnownPeers_Handler,
		},
		{
			MethodName: "LibraryList",
			Handler:    _Raag_LibraryList_Handler,
		},
		{
			MethodName: "LibrarySearch",
			Handler:    _Raag_LibrarySearch_Handler,
		},
		{
			MethodName: "LibraryAdd",
			Handler:    _Raag_LibraryAdd_Handler,
		},
		{
			MethodName: "LibraryRemove",
			Handler:    _Raag_LibraryRemove_Handler,
		},
		{
			MethodName: "LibraryRescan",
			Handler:    _Raag_LibraryRescan_Handler,
		},
		{
			MethodName: "Play",
			Handler:    _Raag_Play_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _Raag_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _Raag_Resume_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Raag_Stop_Handler,
		},
		{
			MethodName: "Next",
			Handler:    _Raag_Next_Handler,
		},
		{
			MethodName: "Previous",
			Handler:    _Raag_Previous_Handler,
		},
		{
			MethodName: "SetVolume",
			Handler:    _Raag_SetVolume_Handler,
		},
		{
			MethodName: "Seek",
			Handler:    _Raag_Seek_Handler,
		},
		{
			MethodName: "GetQueue",
			Handler:    _Raag_GetQueue_Handler,
		},
		{
			MethodName: "NowPlaying",
			Handler:    _Raag_NowPlaying_Handler,
		},
		{
			MethodName: "PlaylistSongs",
			Handler:    _Raag_PlaylistSongs_Handler,
		},
		{
			MethodName: "PlaylistCreate",
			Handler:    _Raag_PlaylistCreate_Handler,
		},
		{
			MethodName: "PlaylistDelete",
			Handler:    _Raag_PlaylistDelete_Handler,
		},
		{
			MethodName: "PlaylistList",
			Handler:    _Raag_PlaylistList_Handler,
		},
		{
			MethodName: "PlaylistAdd",
			Handler:    _Raag_PlaylistAdd_Handler,
		},
		{
			MethodName: "PlaylistRemove",
			Handler:    _Raag_PlaylistRemove_Handler,
		},
		{
			MethodName: "ConfigGet",
			Handler:    _Raag_ConfigGet_Handler,
		},
		{
			MethodName: "ConfigSet",
			Handler:    _Raag_ConfigSet_Handler,
		},
		{
			MethodName: "ConfigReset",
			Handler:    _Raag_ConfigReset_Handler,
		},
		{
			MethodName: "NetworkStatus",
			Handler:    _Raag_NetworkStatus_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Raag_Status_Handler,
		},
		{
			MethodName: "GetFullState",
			Handler:    _Raag_GetFullState_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Raag_Shutdown_Handler,
		},
		{
			MethodName: "ShareSong",
			Handler:    _Raag_ShareSong_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPlayer",
			Handler:       _Raag_WatchPlayer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchPeers",
			Handler:       _Raag_WatchPeers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchTransfers",
			Handler:       _Raag_WatchTransfers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc/proto/raag.proto",
}
