package config

import (
	"bufio"
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"strings"

	"github.com/spf13/viper"
)

type Config struct {
	Library    LibraryConfig    `mapstructure:"library"`
	Playback   PlaybackConfig   `mapstructure:"playback"`
	Daemon     DaemonConfig     `mapstructure:"daemon"`
	P2P        P2PConfig        `mapstructure:"p2p"`
	Transcoder TranscoderConfig `mapstructure:"transcoder"`
	Privacy    PrivacyConfig    `mapstructure:"privacy"`
	Metrics    MetricsConfig    `mapstructure:"metrics"`
}

func Load() (*Config, error) {
	return loadWithOptions("")
}

func LoadWithMusicPath(musicPath string) (*Config, error) {
	return loadWithOptions(musicPath)
}

func loadWithOptions(musicPath string) (*Config, error) {
	v := viper.New()
	v.SetConfigName("config")
	v.SetConfigType("toml")

	configDir := GetConfigDir()
	v.AddConfigPath(configDir)
	v.AddConfigPath(".")

	setDefaults(v)
	if err := v.ReadInConfig(); err != nil {
		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
			return nil, fmt.Errorf("failed to read config: %w", err)
		}
	}

	var cfg Config
	if err := v.Unmarshal(&cfg); err != nil {
		return nil, fmt.Errorf("failed to unmarshal config: %w", err)
	}
	if err := cfg.expandPaths(); err != nil {
		return nil, err
	}
	if musicPath != "" {
		cfg.Library.Paths = []string{ExpandHome(musicPath)}
	}
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	return &cfg, nil
}

func (c *Config) Validate() error {
	if c.P2P.MaxPeers <= 0 {
		c.P2P.MaxPeers = 20
	}
	if c.Playback.Volume < 0 || c.Playback.Volume > 100 {
		c.Playback.Volume = 80
	}
	return nil
}

func (c *Config) ValidateForStart() error {
	if err := c.Validate(); err != nil {
		return err
	}
	if len(c.Library.Paths) == 0 {
		return fmt.Errorf("no music path configured")
	}
	return nil
}

func (c *Config) expandPaths() error {
	c.Daemon.DataDir = ExpandHome(c.Daemon.DataDir)
	c.Daemon.SocketPath = ExpandHome(c.Daemon.SocketPath)
	c.Daemon.PidFile = ExpandHome(c.Daemon.PidFile)
	for i, p := range c.Library.Paths {
		c.Library.Paths[i] = ExpandHome(p)
	}
	return nil
}

func ExpandHome(path string) string {
	if strings.HasPrefix(path, "~/") {
		if usr, err := user.Current(); err == nil {
			return filepath.Join(usr.HomeDir, path[2:])
		}
	}
	return path
}

func GetConfigDir() string {
	return filepath.Join(os.Getenv("HOME"), ".config", "raag")
}

func GetDataDir() string {
	home, _ := os.UserHomeDir()
	if home == "" {
		home = os.Getenv("HOME")
	}
	return filepath.Join(home, ".local", "share", "raag")
}

func RunSetup() error {
	configDir := GetConfigDir()
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	fmt.Println("Welcome to Raag!")
	fmt.Println()

	reader := bufio.NewReader(os.Stdin)
	fmt.Print("Music directory path: ")
	musicPath, _ := reader.ReadString('\n')
	musicPath = strings.TrimSpace(musicPath)
	if musicPath == "" {
		return fmt.Errorf("music path cannot be empty")
	}

	musicPath = ExpandHome(musicPath)
	if _, err := os.Stat(musicPath); os.IsNotExist(err) {
		fmt.Printf("Warning: directory '%s' does not exist\n", musicPath)
		fmt.Print("Create it? [y/N]: ")
		answer, _ := reader.ReadString('\n')
		answer = strings.TrimSpace(strings.ToLower(answer))
		if answer != "y" && answer != "yes" {
			fmt.Println("Setup cancelled")
			return nil
		}
		if err := os.MkdirAll(musicPath, 0o755); err != nil {
			return fmt.Errorf("failed to create directory: %w", err)
		}
	}

	dataDir := GetDataDir()
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return fmt.Errorf("failed to create data directory: %w", err)
	}

	socketPath := filepath.Join(dataDir, "raag.sock")
	pidFile := filepath.Join(dataDir, "raagd.pid")

	configPath := filepath.Join(configDir, "config.toml")
	cfg := fmt.Sprintf(`# Raag Configuration
# Generated by raagd --setup

[library]
paths = ["%s"]
scan_on_start = true
watch = false

[daemon]
socket_path = "%s"
log_level = "info"
data_dir = "%s"
pid_file = "%s"

[playback]
volume = 80
output_device = "default"
buffer_size = 4096
sample_rate = 44100

[p2p]
enabled = false
listen_addrs = ["/ip4/0.0.0.0/tcp/7844"]
mdns_service_tag = "raag-local"
max_peers = 20
stream_port = 7845
announce_library = true
per_peer_rate_limit = 10
upload_bandwidth = 0

[transcoder]
ffmpeg_path = "ffmpeg"
stream_codec = "opus"
stream_bitrate = "128k"

[privacy]
share_library_manifest = true
share_play_history = false
announce_on_discovery = true

[metrics]
enabled = false
port = 9200
path = "/metrics"
`, musicPath, socketPath, dataDir, pidFile)
	if err := os.WriteFile(configPath, []byte(cfg), 0o644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	fmt.Println()
	fmt.Println("Configuration saved to:", configPath)
	fmt.Println()
	fmt.Println("Run 'raagd' to start the daemon")
	fmt.Println("Run 'raag lib scan' to scan your music library")
	return nil
}

type LibraryConfig struct {
	Paths       []string `mapstructure:"paths"`
	ScanOnStart bool     `mapstructure:"scan_on_start"`
	Watch       bool     `mapstructure:"watch"`
}

type PlaybackConfig struct {
	Volume       int    `mapstructure:"volume"`
	OutputDevice string `mapstructure:"output_device"`
	BufferSize   int    `mapstructure:"buffer_size"`
	SampleRate   int    `mapstructure:"sample_rate"`
}

type DaemonConfig struct {
	SocketPath string `mapstructure:"socket_path"`
	LogLevel   string `mapstructure:"log_level"`
	DataDir    string `mapstructure:"data_dir"`
	PidFile    string `mapstructure:"pid_file"`
}

type P2PConfig struct {
	Enabled          bool     `mapstructure:"enabled"`
	ListenAddrs      []string `mapstructure:"listen_addrs"`
	MDNSServiceTag   string   `mapstructure:"mdns_service_tag"`
	MaxPeers         int      `mapstructure:"max_peers"`
	StreamPort       int      `mapstructure:"stream_port"`
	AnnounceLibrary  bool     `mapstructure:"announce_library"`
	PerPeerRateLimit int      `mapstructure:"per_peer_rate_limit"`
	UploadBandwidth  int      `mapstructure:"upload_bandwidth"`
}

type TranscoderConfig struct {
	FFmpegPath    string `mapstructure:"ffmpeg_path"`
	StreamCodec   string `mapstructure:"stream_codec"`
	StreamBitrate string `mapstructure:"stream_bitrate"`
}

type PrivacyConfig struct {
	ShareLibraryManifest bool `mapstructure:"share_library_manifest"`
	SharePlayHistory     bool `mapstructure:"share_play_history"`
	AnnounceOnDiscovery  bool `mapstructure:"announce_on_discovery"`
}

type MetricsConfig struct {
	Enabled bool   `mapstructure:"enabled"`
	Port    int    `mapstructure:"port"`
	Path    string `mapstructure:"path"`
}
